# Dependabot configuration for ChainedSocial ICP project
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Frontend dependencies (npm)
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "miguelrfernandes"
    assignees:
      - "miguelrfernandes"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "frontend"
    ignore:
      # Ignore major version updates for critical dependencies
      - dependency-name: "react"
        update-types: ["version-update:semver-major"]
      - dependency-name: "react-dom"
        update-types: ["version-update:semver-major"]
      - dependency-name: "@dfinity/agent"
        update-types: ["version-update:semver-major"]
      - dependency-name: "@dfinity/auth-client"
        update-types: ["version-update:semver-major"]
      - dependency-name: "@dfinity/identity"
        update-types: ["version-update:semver-major"]
      # Ignore development dependencies that might break builds
      - dependency-name: "vite"
        update-types: ["version-update:semver-major"]
      - dependency-name: "typescript"
        update-types: ["version-update:semver-major"]
      - dependency-name: "eslint"
        update-types: ["version-update:semver-major"]
      - dependency-name: "tailwindcss"
        update-types: ["version-update:semver-major"]

  # Root package.json dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "miguelrfernandes"
    assignees:
      - "miguelrfernandes"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "root"
    ignore:
      # Ignore major version updates for critical tools
      - dependency-name: "dfx"
        update-types: ["version-update:semver-major"]

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "miguelrfernandes"
    assignees:
      - "miguelrfernandes"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"
    ignore:
      # Ignore major version updates for critical actions
      - dependency-name: "actions/checkout"
        update-types: ["version-update:semver-major"]
      - dependency-name: "actions/setup-node"
        update-types: ["version-update:semver-major"]
      - dependency-name: "actions/upload-artifact"
        update-types: ["version-update:semver-major"]
      - dependency-name: "actions/github-script"
        update-types: ["version-update:semver-major"]

  # Docker (if you add containerization later)
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 3
    reviewers:
      - "miguelrfernandes"
    assignees:
      - "miguelrfernandes"
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "docker"

  # Cargo (if you add Rust components later)
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "miguelrfernandes"
    assignees:
      - "miguelrfernandes"
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "rust"
    ignore:
      # Ignore major version updates for critical Rust dependencies
      - dependency-name: "ic-cdk"
        update-types: ["version-update:semver-major"]
      - dependency-name: "ic-cdk-macros"
        update-types: ["version-update:semver-major"] 